spring:
  application:
    name: plazoleta
  datasource:
    url: jdbc:mysql://localhost:3306/PLAZOLETA
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_ACCESS_TOKEN_SECRET}
appDescription: "Plazoleta System"
appVersion: "1.0"

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/