spring:
  application:
    name: plazoleta
  datasource:
    url: jdbc:mysql://localhost:3306/PLAZOLETA
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Plazoleta System"
appVersion: "1.0"

server:
  port: 8081
  servlet:
    context-path: /plazoletaSystem/api/v1
